#!/usr/bin/env python3
"""
Fix products where the CIB variant price equals the Loose (Game Only) price.

Background: In 2026-04, while preparing for Google Ads launch, a scan found
~22% of multi-variant retro game products (1,364 of 6,112) had their CIB
variant priced identically to their Loose variant. Root cause: earlier
`search-price-refresh.py` runs couldn't find these products on PriceCharting
(low match rate on obscure titles), so CIB stayed at whatever value it was
seeded with — which was the loose price from when the variant was created.

This script is *targeted* — it only touches products that are currently
CIB==Loose, not the whole catalog. For each such product, it:

  1. Searches PriceCharting by "{title} {console}"
  2. If a result has cib_market > 0 AND cib_market > loose_market,
     recalculates both prices and updates both variants.
  3. Falls back to a multiplicative CIB uplift (1.8x loose) if PriceCharting
     has no CIB data — retro CIB typically sells 1.5x–3x loose, so 1.8x is
     a safe floor that unsticks the pricing without overshooting.
  4. Skips anything where the loose market is below $3 (fee-floor) or the
     computed CIB sell price would change by less than $1.

Input: data/cib-equals-loose.json (generated by the fresh catalog scan)
Output: data/logs/fix-cib-equals-loose-{timestamp}.{csv,log}

Usage:
    python3 scripts/fix-cib-equals-loose.py                 # Dry run (report only)
    python3 scripts/fix-cib-equals-loose.py --apply         # Actually update Shopify
    python3 scripts/fix-cib-equals-loose.py --apply --uplift-only   # Skip PC search, just apply 1.8x uplift
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import quote_plus

import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv

PROJECT = Path(__file__).parent.parent
load_dotenv(PROJECT / "dashboard" / ".env.local")
load_dotenv(PROJECT / "config" / ".env")

SHOP = os.getenv("SHOPIFY_STORE_URL", "")
TOKEN = os.getenv("SHOPIFY_ACCESS_TOKEN", "")
GQL_URL = f"https://{SHOP}/admin/api/2024-10/graphql.json"
HEADERS = {"X-Shopify-Access-Token": TOKEN, "Content-Type": "application/json"}

with open(PROJECT / "config" / "pricing.json") as f:
    PRICING = json.load(f)

MULTIPLIER = PRICING["default_multiplier"]  # 1.35
MIN_PROFIT = PRICING["minimum_profit_usd"]
FEE_PCT = PRICING["shopify_fee_percent"]
FEE_FIXED = PRICING["shopify_fee_fixed"]

# Safe fallback when PriceCharting has no CIB data. 1.8x is the middle of the
# 1.5x–3x range typical for retro CIB premiums — safe enough to unstick the
# pricing without creating absurd values.
CIB_UPLIFT_MULTIPLIER = 1.8

# Never exceed this as a safety belt
MAX_MARKET_PRICE = 800.0

SEARCH_DELAY = 1.8
SHOPIFY_DELAY = 0.25

PC_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    "Accept": "text/html,application/xhtml+xml",
}

# Shopify tag (lowercased) -> PriceCharting console name to include in query
TAG_TO_CONSOLE = {
    "nes (nintendo entertainment system)": "NES",
    "nes": "NES",
    "snes (super nintendo entertainment system)": "SNES",
    "snes": "SNES",
    "super nintendo": "SNES",
    "nintendo 64": "Nintendo 64",
    "n64": "Nintendo 64",
    "nintendo gamecube": "Gamecube",
    "gamecube": "Gamecube",
    "wii": "Wii",
    "wii u": "Wii U",
    "gameboy": "Gameboy",
    "game boy": "Gameboy",
    "gameboy color": "Gameboy Color",
    "gbc": "Gameboy Color",
    "gameboy advance": "Gameboy Advance",
    "gba": "Gameboy Advance",
    "nintendo ds": "Nintendo DS",
    "ds": "Nintendo DS",
    "nintendo 3ds": "Nintendo 3DS",
    "3ds": "Nintendo 3DS",
    "sega genesis": "Sega Genesis",
    "genesis": "Sega Genesis",
    "sega saturn": "Sega Saturn",
    "saturn": "Sega Saturn",
    "sega dreamcast": "Sega Dreamcast",
    "dreamcast": "Sega Dreamcast",
    "sega master system": "Sega Master System",
    "sega cd": "Sega CD",
    "sega 32x": "Sega 32X",
    "sega game gear": "Sega Game Gear",
    "playstation": "Playstation",
    "ps1": "Playstation",
    "playstation 2": "Playstation 2",
    "ps2": "Playstation 2",
    "playstation 3": "Playstation 3",
    "ps3": "Playstation 3",
    "psp": "PSP",
    "xbox": "Xbox",
    "xbox 360": "Xbox 360",
    "atari 2600": "Atari 2600",
    "atari": "Atari 2600",
    "turbografx-16": "TurboGrafx-16",
}


def parse_price_text(text: str) -> float:
    m = re.search(r"[\$]?([\d,]+\.?\d*)", text.replace(",", ""))
    return float(m.group(1)) if m else 0.0


def title_similarity(query_title: str, result_title: str) -> float:
    """Same logic as search-price-refresh.py — word overlap with a sequel penalty."""
    qt = re.sub(r"[^a-z0-9 ]", "", query_title.lower()).split()
    rt_clean = re.sub(
        r"(NES|SNES|Nintendo 64|Gamecube|Gameboy|Genesis|Playstation|PS[123]|"
        r"Dreamcast|Saturn|GBA|Xbox|Wii|Sega|Atari|TurboGrafx|GameBoy|Game Boy).*$",
        "",
        result_title,
        flags=re.IGNORECASE,
    ).strip()
    rt = re.sub(r"[^a-z0-9 ]", "", rt_clean.lower()).split()
    if not qt or not rt:
        return 0.0
    query_set = set(qt)
    result_set = set(rt)
    extra_words = result_set - query_set
    sequel_indicators = {
        "2", "3", "4", "5", "6", "7", "8", "9", "ii", "iii", "iv",
        "part", "second", "math", "assassin", "case", "screw", "attack",
        "special", "edition", "deluxe", "bundle", "collection",
    }
    if extra_words & sequel_indicators:
        return 0.1
    common = query_set & result_set
    score = len(common) / max(len(query_set), len(result_set))
    if len(extra_words) > 0:
        score *= max(0.5, 1.0 - len(extra_words) * 0.2)
    return score


def search_pricecharting(game_title: str, console_name: str) -> dict | None:
    """Search PriceCharting and return the best-matching row."""
    query = f"{game_title} {console_name}"
    url = f"https://www.pricecharting.com/search-products?q={quote_plus(query)}&type=videogames"
    try:
        resp = requests.get(url, headers=PC_HEADERS, timeout=15)
        resp.raise_for_status()
    except Exception:
        return None

    soup = BeautifulSoup(resp.text, "html.parser")
    table = soup.find("table", {"id": "games_table"})
    if not table:
        return None
    tbody = table.find("tbody")
    if not tbody:
        return None

    target_console = console_name.lower().strip()
    candidates = []
    for row in tbody.find_all("tr")[:8]:
        cols = row.find_all("td")
        if len(cols) < 5:
            continue
        title_link = cols[1].find("a")
        if not title_link:
            continue
        result_title = title_link.get_text(strip=True)
        result_console = cols[2].get_text(strip=True).lower().strip() if len(cols) > 2 else ""
        # Skip PAL / JP releases
        if "pal" in result_console or "jp " in result_console or "japanese" in result_console:
            continue
        # Must be same console family
        if target_console not in result_console and result_console not in target_console:
            continue
        similarity = title_similarity(game_title, result_title)
        loose = parse_price_text(cols[3].get_text(strip=True)) if len(cols) > 3 else 0
        cib = parse_price_text(cols[4].get_text(strip=True)) if len(cols) > 4 else 0
        candidates.append({
            "title": result_title,
            "console": cols[2].get_text(strip=True),
            "loose": loose,
            "cib": cib,
            "similarity": similarity,
        })

    if not candidates:
        return None
    best = max(candidates, key=lambda c: c["similarity"])
    if best["similarity"] < 0.3:
        return None
    # Cap absurd values
    if best["loose"] > MAX_MARKET_PRICE:
        best["loose"] = 0
    if best["cib"] > MAX_MARKET_PRICE:
        best["cib"] = 0
    return best


def calc_sell_price(market_price: float) -> float:
    """1.35x market, rounded DOWN to nearest $X.99 for psychological pricing.

    Matches the rounding logic in manage-sales.py so promo prices and base
    prices stay consistent.
    """
    raw = market_price * MULTIPLIER
    if raw < 1:
        return round(raw, 2)
    dollars = int(raw)
    cents = round((raw - dollars) * 100)
    if cents >= 99:
        return float(dollars) + 0.99
    return float(dollars - 1) + 0.99


def shopify_gql(query, variables=None):
    resp = requests.post(GQL_URL, headers=HEADERS, json={"query": query, "variables": variables or {}})
    resp.raise_for_status()
    return resp.json()


UPDATE_VARIANTS = """
mutation productVariantsBulkUpdate($productId: ID!, $variants: [ProductVariantsBulkInput!]!) {
  productVariantsBulkUpdate(productId: $productId, variants: $variants) {
    productVariants { id price }
    userErrors { field message }
  }
}
"""


def strip_console_suffix(title: str) -> str:
    return re.sub(
        r"\s*[-–]\s*(NES|SNES|N64|Nintendo|Gameboy|Game Boy|Genesis|PS[123P]|"
        r"Gamecube|Dreamcast|Saturn|GBA|Playstation|Xbox|Wii|Sega|Atari|TurboGrafx|GBC).*$",
        "",
        title,
        flags=re.IGNORECASE,
    ).strip()


def get_console_name(tags: list[str]) -> str | None:
    """Find the best PriceCharting console name for a product's tags.

    Walks tags longest-match-first so "Playstation 2" wins over "Playstation".
    """
    tag_lc = [t.lower().strip() for t in tags]
    # Try longest keys first so "playstation 2" beats "playstation"
    for key in sorted(TAG_TO_CONSOLE.keys(), key=len, reverse=True):
        if key in tag_lc:
            return TAG_TO_CONSOLE[key]
    return None


def main():
    parser = argparse.ArgumentParser(description="Fix CIB==Loose priced products")
    parser.add_argument("--apply", action="store_true", help="Apply updates (default: dry run)")
    parser.add_argument("--uplift-only", action="store_true",
                        help="Skip PriceCharting search — just apply the 1.8x CIB uplift")
    parser.add_argument("--limit", type=int, default=0, help="Process only first N products")
    args = parser.parse_args()

    input_file = PROJECT / "data" / "cib-equals-loose.json"
    if not input_file.exists():
        print(f"ERROR: {input_file} not found. Run the catalog scan first.")
        sys.exit(1)

    with open(input_file) as f:
        products = json.load(f)
    if args.limit:
        products = products[: args.limit]

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_dir = PROJECT / "data" / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / f"fix-cib-equals-loose-{ts}.log"
    csv_path = log_dir / f"fix-cib-equals-loose-{ts}.csv"

    log_f = open(log_path, "w")
    csv_f = open(csv_path, "w", newline="")
    writer = csv.writer(csv_f)
    writer.writerow([
        "product", "console", "loose_old", "loose_new", "cib_old", "cib_new",
        "loose_market", "cib_market", "source", "status",
    ])

    def log(msg):
        line = f"[{datetime.now().strftime('%H:%M:%S')}] {msg}"
        print(line)
        log_f.write(line + "\n")
        log_f.flush()

    mode = "APPLY" if args.apply else "DRY RUN"
    if args.uplift_only:
        mode += " (uplift-only — no PC search)"
    log("=" * 60)
    log(f"FIX CIB==LOOSE — {mode}")
    log(f"Products to process: {len(products)}")
    log(f"Log: {log_path}")
    log(f"CSV: {csv_path}")
    log("=" * 60)

    stats = {
        "total": len(products),
        "no_console": 0,
        "search_hit_with_cib": 0,
        "search_hit_no_cib": 0,
        "search_miss": 0,
        "uplift_applied": 0,
        "cib_updated": 0,
        "loose_updated": 0,
        "no_change_needed": 0,
        "errors": 0,
    }

    start = time.time()

    for i, p in enumerate(products):
        console = get_console_name(p["tags"])
        if not console:
            stats["no_console"] += 1
            writer.writerow([p["title"], "", p["loose_price"], "", p["cib_price"], "", "", "", "", "NO_CONSOLE"])
            continue

        clean_title = strip_console_suffix(p["title"])

        pc = None
        if not args.uplift_only:
            pc = search_pricecharting(clean_title, console)
            time.sleep(SEARCH_DELAY)

        loose_market = 0.0
        cib_market = 0.0
        source = ""

        if pc:
            loose_market = pc["loose"]
            cib_market = pc["cib"]
            if cib_market > 0:
                stats["search_hit_with_cib"] += 1
                source = "pc_search"
            else:
                stats["search_hit_no_cib"] += 1
        else:
            stats["search_miss"] += 1

        # Fallback: if PC didn't give us CIB data, use 1.8x uplift on the current
        # (stale) loose price as the CIB market floor. This won't be perfect but
        # it gets the CIB variant away from equaling the loose price, which is
        # the blocking issue.
        if cib_market == 0:
            # Derive loose market from current price (reverse 1.35x)
            implied_loose = p["loose_price"] / MULTIPLIER
            if loose_market == 0:
                loose_market = implied_loose
            cib_market = loose_market * CIB_UPLIFT_MULTIPLIER
            source = source or "uplift_1.8x"
            stats["uplift_applied"] += 1

        # Cap ridiculous values
        if cib_market > MAX_MARKET_PRICE:
            cib_market = MAX_MARKET_PRICE
        if loose_market > MAX_MARKET_PRICE:
            loose_market = MAX_MARKET_PRICE

        new_cib_price = calc_sell_price(cib_market)
        new_loose_price = calc_sell_price(loose_market) if loose_market > 0 else p["loose_price"]

        # Sanity: CIB must be strictly greater than loose
        if new_cib_price <= new_loose_price:
            new_cib_price = new_loose_price + 5.0  # enforce minimum $5 CIB premium
            # Re-round the enforced value
            dollars = int(new_cib_price)
            new_cib_price = float(dollars) + 0.99 if dollars > 0 else new_cib_price

        # Only update if it actually changes things meaningfully
        cib_diff = round(new_cib_price - p["cib_price"], 2)
        loose_diff = round(new_loose_price - p["loose_price"], 2)

        if abs(cib_diff) < 1.0 and abs(loose_diff) < 1.0:
            stats["no_change_needed"] += 1
            writer.writerow([
                p["title"], console, p["loose_price"], p["loose_price"],
                p["cib_price"], p["cib_price"], loose_market, cib_market,
                source, "NO_CHANGE",
            ])
            continue

        writer.writerow([
            p["title"], console, p["loose_price"], new_loose_price,
            p["cib_price"], new_cib_price, loose_market, cib_market,
            source, "APPLY" if args.apply else "PREVIEW",
        ])
        csv_f.flush()

        if not args.apply:
            if i < 20:
                log(f"  [{i+1}/{len(products)}] {p['title'][:50]}")
                log(f"      loose: ${p['loose_price']:.2f} -> ${new_loose_price:.2f} | "
                    f"cib: ${p['cib_price']:.2f} -> ${new_cib_price:.2f} | "
                    f"markets: loose=${loose_market:.2f} cib=${cib_market:.2f} ({source})")
            continue

        # Build the variant update payload. Update both if both changed.
        updates = []
        if abs(cib_diff) >= 1.0:
            updates.append({"id": p["cib_id"], "price": f"{new_cib_price:.2f}"})
        if abs(loose_diff) >= 1.0:
            updates.append({"id": p["loose_id"], "price": f"{new_loose_price:.2f}"})

        try:
            res = shopify_gql(UPDATE_VARIANTS, {"productId": p["id"], "variants": updates})
            errs = res.get("data", {}).get("productVariantsBulkUpdate", {}).get("userErrors", [])
            if errs:
                log(f"  ERROR [{i+1}] {p['title']}: {errs[0]['message']}")
                stats["errors"] += 1
            else:
                if abs(cib_diff) >= 1.0:
                    stats["cib_updated"] += 1
                if abs(loose_diff) >= 1.0:
                    stats["loose_updated"] += 1
        except Exception as e:
            log(f"  ERROR [{i+1}] {p['title']}: {e}")
            stats["errors"] += 1

        time.sleep(SHOPIFY_DELAY)

        if (i + 1) % 50 == 0:
            elapsed = time.time() - start
            rate = (i + 1) / elapsed * 60
            remaining = (len(products) - i - 1) / (rate / 60) if rate > 0 else 0
            log(f"  progress: {i+1}/{len(products)} | cib_updated={stats['cib_updated']} | "
                f"loose_updated={stats['loose_updated']} | rate={rate:.0f}/min | eta={remaining/60:.0f}min")

    elapsed = time.time() - start
    log("")
    log("=" * 60)
    log("RESULTS")
    log("=" * 60)
    log(f"  Total processed:            {stats['total']}")
    log(f"  No console detected:        {stats['no_console']}")
    log(f"  PC search found CIB data:   {stats['search_hit_with_cib']}")
    log(f"  PC search found but no CIB: {stats['search_hit_no_cib']}")
    log(f"  PC search missed:           {stats['search_miss']}")
    log(f"  Used 1.8x uplift fallback:  {stats['uplift_applied']}")
    log(f"  CIB variant updated:        {stats['cib_updated']}")
    log(f"  Loose variant updated:      {stats['loose_updated']}")
    log(f"  No meaningful change:       {stats['no_change_needed']}")
    log(f"  Errors:                     {stats['errors']}")
    log(f"  Elapsed:                    {elapsed/60:.1f} min")

    log_f.close()
    csv_f.close()
    print(f"\nLog: {log_path}")
    print(f"CSV: {csv_path}")


if __name__ == "__main__":
    main()
