#!/usr/bin/env python3
"""
Fix the 694 products where `category:console` is set but the product is
actually a game. Reads data/miscategorized-products.json (generated by
check-category-tags.py) and replaces the bad tag via Shopify GraphQL.

Usage:
    python3 scripts/fix-miscategorized-tags.py --dry-run
    python3 scripts/fix-miscategorized-tags.py
"""
import json
import os
import sys
import time
import requests
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / "dashboard" / ".env.local")
load_dotenv(Path(__file__).parent.parent / "config" / ".env")

SHOP = os.getenv("SHOPIFY_STORE_URL", "")
TOKEN = os.getenv("SHOPIFY_ACCESS_TOKEN", "")
API_VERSION = "2024-10"
GQL_URL = f"https://{SHOP}/admin/api/{API_VERSION}/graphql.json"
HEADERS = {"X-Shopify-Access-Token": TOKEN, "Content-Type": "application/json"}

DRY_RUN = "--dry-run" in sys.argv


def gql(query, variables=None):
    for attempt in range(5):
        resp = requests.post(GQL_URL, headers=HEADERS, json={"query": query, "variables": variables or {}})
        if resp.status_code != 200:
            time.sleep(2 ** attempt)
            continue
        data = resp.json()
        errs = data.get("errors", [])
        if any(e.get("extensions", {}).get("code") == "THROTTLED" for e in errs):
            time.sleep(2 ** attempt)
            continue
        return data
    return data


UPDATE_TAGS_MUTATION = """
mutation UpdateTags($id: ID!, $tags: [String!]!) {
  productUpdate(input: {id: $id, tags: $tags}) {
    product { id tags }
    userErrors { field message }
  }
}
"""

GET_TAGS_QUERY = """
query($id: ID!) {
  product(id: $id) { id tags }
}
"""


def main():
    data_path = Path(__file__).parent.parent / "data" / "miscategorized-products.json"
    if not data_path.exists():
        print(f"ERROR: {data_path} not found. Run check-category-tags.py --save first.")
        sys.exit(1)

    miscategorized = json.loads(data_path.read_text())
    print(f"Loaded {len(miscategorized)} miscategorized products")
    if DRY_RUN:
        print("[DRY RUN — no mutations will be sent]\n")

    fixed = 0
    skipped = 0
    errors = 0

    for i, p in enumerate(miscategorized, 1):
        pid = p["id"]
        title = p["title"]

        # Fetch current tags (they may have changed since the scan)
        result = gql(GET_TAGS_QUERY, {"id": pid})
        node = result.get("data", {}).get("product")
        if not node:
            print(f"  [{i}] SKIP {title}: not found")
            skipped += 1
            continue

        current_tags = node["tags"]
        if "category:console" not in current_tags:
            print(f"  [{i}] SKIP {title}: no longer tagged category:console")
            skipped += 1
            continue

        # Replace category:console with category:game
        new_tags = [t for t in current_tags if t != "category:console"]
        if "category:game" not in new_tags:
            new_tags.append("category:game")

        if DRY_RUN:
            print(f"  [{i}] WOULD FIX {title}")
            fixed += 1
            continue

        result = gql(UPDATE_TAGS_MUTATION, {"id": pid, "tags": new_tags})
        user_errors = result.get("data", {}).get("productUpdate", {}).get("userErrors", [])
        if user_errors:
            print(f"  [{i}] ERROR {title}: {user_errors}")
            errors += 1
        else:
            fixed += 1
            if i % 50 == 0:
                print(f"  [{i}/{len(miscategorized)}] {fixed} fixed so far...")

        time.sleep(0.5)

    print(f"\n{'DRY RUN ' if DRY_RUN else ''}Summary:")
    print(f"  Fixed:   {fixed}")
    print(f"  Skipped: {skipped}")
    print(f"  Errors:  {errors}")


if __name__ == "__main__":
    main()
